[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.3.1"
  export = ["greeting_service_rj"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/Service","Category/Service","Internal/http"]
  name = "greeting_service_rj"
  org = "medinetpdp"
  version = "3.1.1"

